
/* Drop Tables */

DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS LOGRADOURO;
DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS LOCALIDADE;
DROP TABLE IF EXISTS CODIGO_POSTAL;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS TELEFONE;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS TIPO_EMAIL;
DROP TABLE IF EXISTS TIPO_ENDERECO;
DROP TABLE IF EXISTS TIPO_LOGRADOURO;
DROP TABLE IF EXISTS TIPO_TELEFONE;
DROP TABLE IF EXISTS USUARIO;




/* Create Tables */

CREATE TABLE BAIRRO
(
	ID numeric NOT NULL,
	ID_LOCALIDADE numeric NOT NULL,
	DESCRICAO varchar,
	DESCRICAO_REDUZIDA varchar,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CODIGO_POSTAL
(
	ID numeric NOT NULL,
	CODIGO varchar NOT NULL,
	-- 0 = localidade; 
	-- 1 = logradouro; 
	-- 2 = distrito/povoado;
	-- 3 = caixa postal comunitaria; 
	-- 4 = grandes usuarios; 
	-- 5 = unidades operacionais;
	-- 
	TIPO varchar(1) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE EMAIL
(
	ID numeric NOT NULL,
	-- Chave Primária
	ID_PESSOA numeric NOT NULL,
	ID_TIPO_EMAIL numeric NOT NULL,
	DESCRICAO varchar,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ENDERECO
(
	ID numeric NOT NULL,
	-- Chave Primária
	ID_PESSOA numeric NOT NULL,
	-- Residencial
	-- Comercial
	-- Outros...
	ID_TIPO_ENDERECO numeric NOT NULL,
	ID_LOGRADOURO numeric NOT NULL,
	NUMERO varchar DEFAULT 'S/N' NOT NULL,
	COPLEMENTO varchar,
	PONTO_REFERENCIA varchar,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ESTADO
(
	ID numeric NOT NULL,
	ID_PAIS numeric NOT NULL,
	SIGLA varchar NOT NULL,
	DESCRICAO varchar NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE FUNCIONARIO
(
	ID numeric NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOCALIDADE
(
	ID numeric NOT NULL,
	ID_CODIGO_POSTAL numeric NOT NULL,
	ID_ESTADO numeric NOT NULL,
	DESCRICAO varchar NOT NULL,
	DESCRICAO_REDUZIDA varchar NOT NULL,
	CODIGO_IBGE varchar NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOGRADOURO
(
	ID numeric NOT NULL,
	ID_TIPO_LOGRADOURO numeric NOT NULL,
	ID_CODIGO_POSTAL numeric NOT NULL,
	ID_BAIRRO_INICIAL numeric NOT NULL,
	ID_BAIRRO_FINAL numeric,
	DESCRICAO varchar NOT NULL,
	DESCRICAO_REDUZIDA varchar NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PAIS
(
	ID numeric NOT NULL,
	CODIGO varchar NOT NULL,
	SIGLA varchar NOT NULL,
	DESCRICAO varchar(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PESSOA
(
	-- Chave Primária
	ID numeric NOT NULL,
	-- Nome da Pessoa
	NOME varchar(200) NOT NULL,
	-- Número do cadastro de pessoa física
	CPF varchar(11) NOT NULL,
	DATA_NASCIMENTO date NOT NULL,
	-- M
	-- F
	-- N - Nenhum
	SEXO varchar(1),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TELEFONE
(
	ID numeric NOT NULL,
	-- Chave Primária
	ID_PESSOA numeric NOT NULL,
	ID_TIPO_TELEFONE numeric NOT NULL,
	NUMERO numeric NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_EMAIL
(
	ID numeric NOT NULL,
	DESCRICAO varchar(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_ENDERECO
(
	ID numeric NOT NULL,
	-- Residencial
	-- Comercial
	-- Outros... (O usuário poderá criar)
	DESCRICAO varchar(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_LOGRADOURO
(
	ID numeric NOT NULL,
	-- rua
	-- praça
	-- avenida
	-- ...
	-- ...
	-- ...
	DESCRICAO varchar(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_TELEFONE
(
	ID numeric NOT NULL,
	-- Residencial
	-- Comercial
	-- Celular
	-- Outros (o usuário poderá cadastrar)
	-- 
	DESCRICAO varchar(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE USUARIO
(
	ID numeric NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE LOGRADOURO
	ADD FOREIGN KEY (ID_BAIRRO_FINAL)
	REFERENCES BAIRRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOGRADOURO
	ADD FOREIGN KEY (ID_BAIRRO_INICIAL)
	REFERENCES BAIRRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOCALIDADE
	ADD FOREIGN KEY (ID_CODIGO_POSTAL)
	REFERENCES CODIGO_POSTAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOGRADOURO
	ADD FOREIGN KEY (ID_CODIGO_POSTAL)
	REFERENCES CODIGO_POSTAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOCALIDADE
	ADD FOREIGN KEY (ID_ESTADO)
	REFERENCES ESTADO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BAIRRO
	ADD FOREIGN KEY (ID_LOCALIDADE)
	REFERENCES LOCALIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_LOGRADOURO)
	REFERENCES LOGRADOURO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESTADO
	ADD FOREIGN KEY (ID_PAIS)
	REFERENCES PAIS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_PESSOA)
	REFERENCES PESSOA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TELEFONE
	ADD FOREIGN KEY (ID_PESSOA)
	REFERENCES PESSOA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMAIL
	ADD FOREIGN KEY (ID_PESSOA)
	REFERENCES PESSOA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMAIL
	ADD FOREIGN KEY (ID_TIPO_EMAIL)
	REFERENCES TIPO_EMAIL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_TIPO_ENDERECO)
	REFERENCES TIPO_ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOGRADOURO
	ADD FOREIGN KEY (ID_TIPO_LOGRADOURO)
	REFERENCES TIPO_LOGRADOURO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TELEFONE
	ADD FOREIGN KEY (ID_TIPO_TELEFONE)
	REFERENCES TIPO_TELEFONE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN CODIGO_POSTAL.TIPO IS '0 = localidade; 
1 = logradouro; 
2 = distrito/povoado;
3 = caixa postal comunitaria; 
4 = grandes usuarios; 
5 = unidades operacionais;
';
COMMENT ON COLUMN EMAIL.ID_PESSOA IS 'Chave Primária';
COMMENT ON COLUMN ENDERECO.ID_PESSOA IS 'Chave Primária';
COMMENT ON COLUMN ENDERECO.ID_TIPO_ENDERECO IS 'Residencial
Comercial
Outros...';
COMMENT ON COLUMN PESSOA.ID IS 'Chave Primária';
COMMENT ON COLUMN PESSOA.NOME IS 'Nome da Pessoa';
COMMENT ON COLUMN PESSOA.CPF IS 'Número do cadastro de pessoa física';
COMMENT ON COLUMN PESSOA.SEXO IS 'M
F
N - Nenhum';
COMMENT ON COLUMN TELEFONE.ID_PESSOA IS 'Chave Primária';
COMMENT ON COLUMN TIPO_ENDERECO.DESCRICAO IS 'Residencial
Comercial
Outros... (O usuário poderá criar)';
COMMENT ON COLUMN TIPO_LOGRADOURO.DESCRICAO IS 'rua
praça
avenida
...
...
...';
COMMENT ON COLUMN TIPO_TELEFONE.DESCRICAO IS 'Residencial
Comercial
Celular
Outros (o usuário poderá cadastrar)
';



