
/* Drop Tables */

DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS TIPO_LOGRADOURO;




/* Create Tables */

CREATE TABLE BAIRRO
(

) WITHOUT OIDS;


CREATE TABLE ENDERECO
(
	ID numeric NOT NULL,
	-- Chave Primária
	ID_PESSOA numeric NOT NULL,
	ID_TIPO_LOGRADOURO numeric NOT NULL,
	CEP numeric(8) NOT NULL,
	-- 1. Residencial
	-- 2. Comercial
	-- 3. Outros
	TIPO_ENDERECO varchar(1) NOT NULL,
	LOGRADOURO varchar(1000) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ESTADO
(

) WITHOUT OIDS;


CREATE TABLE MUNICIPIO
(

) WITHOUT OIDS;


CREATE TABLE PAIS
(

) WITHOUT OIDS;


CREATE TABLE PESSOA
(
	-- Chave Primária
	ID numeric NOT NULL,
	-- Nome da Pessoa
	NAME varchar(200) NOT NULL,
	-- Número do cadastro de pessoa física
	CPF numeric(11),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_LOGRADOURO
(
	ID numeric NOT NULL,
	DESCRICAO varchar(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_PESSOA)
	REFERENCES PESSOA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_TIPO_LOGRADOURO)
	REFERENCES TIPO_LOGRADOURO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN ENDERECO.ID_PESSOA IS 'Chave Primária';
COMMENT ON COLUMN ENDERECO.TIPO_ENDERECO IS '1. Residencial
2. Comercial
3. Outros';
COMMENT ON COLUMN PESSOA.ID IS 'Chave Primária';
COMMENT ON COLUMN PESSOA.NAME IS 'Nome da Pessoa';
COMMENT ON COLUMN PESSOA.CPF IS 'Número do cadastro de pessoa física';



